folder: "scenario/baseline"

paths:
  network: "${folder}/network.xml"
  plan:  "${folder}/Siouxfalls_population.xml"
  events: "${folder}/output_events.xml"
  trips: "${folder}/output_trips.csv"
  legs: "${folder}/output_legs.csv"
  plan_output: "${folder}/output_plans.xml"
  transit_vehicle: "${folder}/output_transitVehicles.xml"
  transit_schedule: "${folder}/output_transitSchedule.xml"

data:
  interim:  
    event:
      person_enter_bus: "data/interim/event/person_enter_bus.arrow"
      travel_time_all_vehicle: "data/interim/event/travel_time_all_vehicle.arrow"
      bus_delay_at_facilities: "data/interim/event/bus_delay_at_facilities.arrow"
      people_trip: "data/interim/event/people_trip.arrow"

