scenario: "after"
scenario_list: ["baseline", "after"]

paths:
  network: "scenario/${scenario}/network.xml"
  plan:  "scenario/${scenario}/plans_scale0.375true.xml"
  events: "scenario/${scenario}/output_events.xml"
  trips: "scenario/${scenario}/output_trips.csv"
  legs: "scenario/${scenario}/output_legs.csv"
  plan_output: "scenario/${scenario}/output_plans.xml"
  transit_vehicle: "scenario/${scenario}/output_transitVehicles.xml"
  transit_schedule: "scenario/${scenario}/output_transitSchedule.xml"

data:
  interim: 
    event:
      person_enter_bus: "data/interim/${scenario}/event/person_enter_bus.arrow"
      travel_time_all_vehicle: "data/interim/${scenario}/event/travel_time_all_vehicle.arrow"
      bus_delay_at_facilities: "data/interim/${scenario}/event/bus_delay_at_facilities.arrow"
      people_trip: "data/interim/${scenario}/event/people_trip.arrow"
      bus_trip: "data/interim/${scenario}/event/bus_trip.arrow"
    visualize:
      bus_heatmap: "data/visualize/${scenario}/bus_od_heatmap.png"
      od_heatmap: "data/visualize/${scenario}/od_heatmap.png"
      person_trip_analysis: "data/visualize/${scenario}/person_trip_analysis"
    
  processed:
    kpi_result: "data/processed/${scenario}/kpi_result.txt"
    all_kpi_result: "data/processed/all_kpi_result.txt"

  comparasion:
    comparison_folder : "data/visualize/comparison"
    


